# Generated by Django 3.1.2 on 2020-10-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201013_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referral_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.account'),
        ),
    ]
