# Generated by Django 3.1.2 on 2020-10-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_account_referral_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='referral_fk',
            new_name='referer_fk',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='registration_ref_code',
            new_name='referral_code',
        ),
    ]
