# Generated by Django 3.1.2 on 2020-10-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201013_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='referer_fk',
            new_name='referrer_fk',
        ),
    ]
